 export const HOTEL_FACILITIES = [
  'Free parking',
  'Free wifi',
  'Pool',
  'Pet friendly',
  'Playground',
  'Restaurant',
  'Bar',
  'Gym',
  'Spa',
  'Beachfront',
  'Airport shuttle',
  'Family rooms',
  'Facilities for disabled guests',
  'Non-smoking rooms',
  'Room service',
  'Air conditioning',
  'Daily housekeeping',
  'Private bathroom',
  'Flat-screen TV',
  'Balcony',
  'Terrace',
  'Mountain view',
  'City view',
  'Sea view',
  'Coffee maker',
  'Kitchen',
];
