enum QueryKey  {
  USER= "LOGEDIN_USER",
  HOTELS= "HOTELS",
  HOTEL= "HOTEL",
  BOOKINGS= "BOOKINGS",
  ALL_USERS= "ALL_USERS",
  ROOMS= "ROOMS",
  ROOM= "ROOM",
  POPULAR_HOTELS= "PUPULANE_HOTELS",
  COUNT_ALL_DOCS= "COUNT_ALL_DOCS",
  HOTEL_STATS= "HOTEL_STATS",
};

export default QueryKey;
